### ISSUE TITLE
Hive metastore支持utf8

### ISSUE THREAD

**Issue by mattshma** [mattshma/bigdata#11]
hive元数据存储在mysql，在创建表时，若`comment`为中文，将无法创建表。这里说下解决方案。
## 修改元数据表定义
- 修改表字段注释：`alter table COLUMNS_V2 modify column COMMENT varchar(256) character set utf8;`。
- 修改表注释：`alter table TABLE_PARAMS modify column PARAM_VALUE varchar(4000) character set utf8;`。
- 修改分区字段：`alter table PARTITION_PARAMS  modify column PARAM_VALUE varchar(4000) character set utf8;`和`alter table PARTITION_KEYS  modify column PKEY_COMMENT varchar(4000) character set utf8`。
- 修改索引注释：`alter table  INDEX_PARAMS  modify column PARAM_VALUE  varchar(4000) character set utf8;`。

修改完后，能支持中文建表，插入，desc table也是正常的，但通过show create table和select查出来的结果仍是乱码。

**Comment by mattshma** [comment]
[同样问题](https://segmentfault.com/q/1010000000730934)。todo。

**Comment by utf7** [comment]
https://issues.apache.org/jira/browse/HIVE-11837 Hive的bug。
