### ISSUE TITLE
Orphaned pod found, but volume paths are still present on disk

### ISSUE THREAD

**Issue by mattshma** [mattshma/bigdata#114]
机器因故自动重启后，Kubelet 等都启动正常，不过无法获取该机器上的 gpu 信息。查看 kubelet log，有如下报错：
```
May 17 16:45:26 kubelet[3292]: E0517 16:45:26.176639    3292 kubelet_volumes.go:128] Orphaned pod "69d873c0-5324-11e8-9843-005056b76c14" found, but volume paths are still present on disk : There were a total of 2 errors similar to this. Turn up verbosity to see them.
```
由于该机器上的 pod 等都没在使用，所以相关的 volume 信息应该删除，停掉 kubelet, kube-proxy 等服务后，删除 `/var/lib/k8s/kubelet/pods` 下的各目录即可。然后启动 kubelet, kube-proxy。恢复正常。

**Comment by mattshma** [comment]
D: https://github.com/kubernetes/kubernetes/issues/60987

**Comment by NightmareZero** [comment]
@mattshma 最好不要这么干，因为如果有pvc的话，rm -rf pod会顺便吧pvc里面的内容干掉，回收pod不是这么干的。

**Comment by mattshma** [comment]
@NightmareZero 删除 POD 确实不是这么删除的。不过我这里删除的是 Orphaned pod，如果不这么删，请问下是否还有其他更好的删除方法么？如果有的话麻烦告知下，谢谢~

**Comment by NightmareZero** [comment]
只是提醒一下，先umount，我是被坑惨了，数据库里面的数据都清空了

**Comment by mattshma** [comment]
@NightmareZero 额，我存储使用的 rbd，直接删除的话，数据在 rbd 还是有的，没出现你说的这种情况。

**Comment by NightmareZero** [comment]
我用的也是rbd，用rm -rf的话，会导致rbd mount出来的设备删不掉，但是里面的内容被删干净的情况
你可以做做试验在/mnt/test/t1挂个设备，然后rm -rf /mnt/test试试，t1里面的数据会被清空的

**Comment by mattshma** [comment]
@NightmareZero mount上去再 rm -rf，当然会删除，这个我清楚。我理解你的意思了，可能当时我的 rbd 在某步已经 umount 了。多谢指教！

想请假下，你有做过多节点挂载存储么？

**Comment by NightmareZero** [comment]
做了，不过用的不是rbd，用的是cephfs

**Comment by mattshma** [comment]
哦，这样。

**Comment by xigang** [comment]
> @mattshma 最好不要这么干，因为如果有pvc的话，rm -rf pod会顺便吧pvc里面的内容干掉，回收pod不是这么干的。

赞同你的观点：）
