### ISSUE TITLE
health HEALTH_WARN 64 pgs incomplete; 64 pgs stuck inactive; 64 pgs stuck unclean

### ISSUE THREAD

**Issue by mattshma** [mattshma/bigdata#95]
在根据[文档](http://docs.ceph.com/docs/master/start/quick-ceph-deploy/)操作过程中，查看 ceph 状态异常：
```
$ ceph -w
    cluster 78abe680-037c-47a3-872e-cd2858ec11ce
     health HEALTH_ERR
            64 pgs are stuck inactive for more than 300 seconds
            64 pgs stuck inactive
$ ceph osd tree
ID WEIGHT  TYPE NAME              UP/DOWN REWEIGHT PRIMARY-AFFINITY
-1 0.51859 root default
-2 0.25929     host svr002
 0 0.25929         osd.0             down        0          1.00000
-3 0.25929     host svr003
 1 0.25929         osd.1             down        0          1.00000
```

使用的操作系统为 CentOS7，文件系统为 ext4，根据[文档](http://docs.ceph.com/docs/jewel/rados/configuration/filesystem-recommendations/)说明应在 ceph.conf 中添加如下行：
```
osd max object name len = 256
osd max object namespace len = 64
```

然后通过 `ceph-deploy --overwrite-conf admin svr002 svr003`将配置推送给所有 osd 节点，确保 osd 节点上 ceph 用户对 `/etc/ceph/ceph.client.admin.keyring` 有可读权限：`sudo chmod +r /etc/ceph/ceph.client.admin.keyring`后，重新启动 osd 节点：`ceph-deploy osd activate svr002:/opt/data/osd2 svr003:/opt/data/osd3`即可。

*说明，本过程已在 [ceph-cookbook-issue187](https://github.com/ceph/ceph-cookbook/issues/187)中进行了说明，为防止之后重新遇到问题，这里简单记录下。*

**Comment by rimadhu** [comment]
ceph -s
    cluster 421141d3-dc29-43e3-8dbf-c61965cf3f73
     health HEALTH_ERR
            64 pgs are stuck inactive for more than 300 seconds
            64 pgs degraded
            64 pgs stale
            64 pgs stuck degraded
            64 pgs stuck stale
            64 pgs stuck unclean
            64 pgs stuck undersized
            64 pgs undersized
            too few PGs per OSD (16 < min 30)
     monmap e1: 4 mons at {admin=115.124.99.51:6789/0,node0=115.124.99.53:6789/0,node1=115.124.99.54:6789/0,node2=115.124.99.58:6789/0}
            election epoch 16, quorum 0,1,2,3 admin,node0,node1,node2
     osdmap e29: 4 osds: 4 up, 4 in; 18 remapped pgs
            flags sortbitwise,require_jewel_osds
      pgmap v106: 64 pgs, 1 pools, 0 bytes data, 0 objects
            131 MB used, 77648 MB / 77779 MB avail
                  64 stale+active+undersized+degraded
