### ISSUE TITLE
启动 docker 时报错：`Error response from daemon: mkdir xxxx:  invalid argument`

### ISSUE THREAD

**Issue by mattshma** [mattshma/bigdata#97]
报错如下：
```
$ sudo docker run -t -i ubuntu:14.04 /bin/bash
docker: Error response from daemon: mkdir /var/lib/docker/overlay/ea2c9b86f1ebaba280f9fdba6437e9a3fede07562656dd0502fb8ef9cce81684-init/merged/dev/shm: invalid argument.
See 'docker run --help'.
```

查了下，和 storage driver 有关，根据 [Select a storage driver
](https://docs.docker.com/engine/userguide/storagedriver/selectadriver/#docker-ce) 是推荐，CentOS 建议使用 `devicemapper` 和 `vfs`。修改/etc/docker/daemon.json，内容如下:
```
{
  "storage-driver": "devicemapper"
}
```

重启 docker 即可。

**Comment by chenyongze** [comment]
docker run -d --name shengle-xunsearch -p 18383:8383 -p 18384:8384 hightman/xunsearch:latest
/usr/bin/docker-current: Error response from daemon: mkdir /var/lib/docker/overlay2/e1f741f426ea51df477808fd9b90123369b8848fdccc3a4af17849554480dd25-init/merged/dev/shm: invalid argument.
See '/usr/bin/docker-current run --help'.
